### ISSUE TITLE
Clean up yaml config

### ISSUE THREAD

**Issue by bheijden** [eager-dev/eager#146]
Make yaml definition consistent for different engines (webots, gazebo, etc..)

For example, the pybullet definitions for an actuator is:
```
  actuators:
    joints:
      type: joint
      names: [shoulder_pan_joint, shoulder_lift_joint, elbow_joint, wrist_1_joint, wrist_2_joint, wrist_3_joint]
```
while webots is
```
  actuators:
    joints:
      names:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
```

My preference goes out to Pybullet definition as it uses less lines (at the cost of each line being slightly less readable), which I find cleaner.
